# Donation / Sponsorship Links for SkripsiMate

# GitHub Sponsors (uncomment when available)
# github: XenchinRyu7

# Trakteer (Indonesian donation platform)
custom: ['https://trakteer.id/saefulrohman', 'https://saweria.co/saefulrohman']

# Other platforms (uncomment and add if applicable)
# patreon: yourusername
# ko_fi: yourusername
# buy_me_a_coffee: yourusername
# paypal: yourusername

